### ISSUE TITLE
Maquetado del header

### ISSUE THREAD

**Issue by santoyomontoyar** [santoyomontoyar/travel-segundo-parcial#3]
La sección del header se compone de 3 datos

- Logotipo 
- Menú
- Acciones 

Dicho apartado debe de_

- [ ] Ser responsivo 
- [ ] Al dar scroll el fondo cambie a blanco

![image](https://github.com/user-attachments/assets/18e1562d-f02b-4bea-a73b-8483bcff7cc9)

**Comment by alexx-canul** [comment]
fixes https://github.com/santoyomontoyar/travel-segundo-parcial/issues/3

subiendo maquetado del header incluyendo:

1. logotipo
2. menú
3. acciones

<img width="1440" alt="Captura de pantalla 2024-10-29 a la(s) 19 46 07" src="https://github.com/user-attachments/assets/915b5a9e-6a8a-449d-a6c3-ec7a2b535566">
